### ISSUE TITLE
Abgabe Praktikum 3

### ISSUE THREAD

**Issue by Flusinerd** [Flusinerd/OpSa2#1]
Praktikum 3 - Observable und Singleton

@stebir 
@UrsulaOesing

**Comment by Flusinerd** [comment]
Closed with 152b672

**Comment by stebir** [comment]
Ihre Klasse Sportstättencontrol ist kein Observer, bitte korrigieren!
Sonst OK

**Comment by Flusinerd** [comment]
@stebir Gefixt mit https://github.com/Flusinerd/OpSa2/commit/afd5606b72ff9c430ee770bb5a5a3aecc1f4e03b

**Comment by stebir** [comment]
Praktikum Modul 3 bestanden
